### ISSUE TITLE
マップのBAN機能

### ISSUE THREAD

**Issue by secchanu** [KU-eSports/kuest-streaming#32]
# マップのBAN機能

## 概要
- 両チームがそれぞれBANするマップを選べる機能が欲しい
- BANされたマップは抽選対象から除外される
- 選択されたマップが被った場合は1マップのみのBANとなる
- 配信画面にBANされたマップが表示されるようにする
- 2マップBANの場合と1マップBANの場合とBANなしの場合の3通りの画面を作る

## やること
- Killjoyボットのコードを編集する
- NodeCGのコードを編集する

## 仕様
- /ban "マップ名" でBANマップが設定できるようにする
- /ban reset でリセット
- 正しく設定できたら「"マップ名"がBANされました」とbotがチャットを打つようにする

_Originally posted by @ykmtsd in https://github.com/KU-eSports/kuest-streaming/issues/27#issuecomment-1186214258_

Discordの仕様上`/ban`と`/ban reset`のコマンドは共存できないのでコマンド名についても検討必要

**Comment by secchanu** [comment]
> /ban と /ban reset が共存できないのは、スペースはコマンドで使えないからですか？ [#32 (comment)](https://github.com/KU-eSports/kuest-streaming/issues/32#issue-1308937498)

チャットに/banまで入力した場合に後ろに"マップ名"が来るのかresetが来るのか判別できないからです
具体的な例だと"reset"っていう名前のマップがあったとしたらそのマップはBANできなくなっちゃいますよね

参考: [Subcommands and Subcommand Groups](https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups)
このDiscordのdocsに仕様とか書いてあるので読んでみてください

**Comment by ykmtsd** [comment]
# マップのBAN機能実装

## 概要
- 両チームがそれぞれBANするマップを選べる機能が欲しい
- BANされたマップは抽選対象から除外される
- 選択されたマップが被った場合は1マップのみのBANとなる
- 配信画面にBANされたマップが表示されるようにする
- 2マップBANの場合と1マップBANの場合とBANなしの場合の3通りの画面を作る

## やること
- Killjoyボットのコードを編集する
- NodeCGのコードを編集する

## 仕様
- /ban "マップ名" でBANマップが設定できるようにする
- ~~/ban reset でリセット~~ → /banreset でリセット
- 正しく設定できたら「"マップ名"がBANされました」とbotがチャットを打つようにする

更新日

2022/7/19

**Comment by secchanu** [comment]
一番上のコメント @ykmtsd が書き換えられる方が更新していきやすいと思うので一回立てちゃったんですけどissue立て直してもらっても良いですか？
