### ISSUE TITLE
マップのBAN機能

### ISSUE THREAD

**Issue by ykmtsd** [KU-eSports/kuest-streaming#34]
# マップのBAN機能実装

## 概要
- 両チームがそれぞれBANするマップを選べる機能が欲しい
- BANされたマップは抽選対象から除外される
- 選択されたマップが被った場合は1マップのみのBANとなる
- BANなしも選択可(BANフェーズに何もしなければok)
- 配信画面にはBANされたマップの画像が表示される

## やること
- Killjoyボットのコードを移植するbotディレクトリに←完了
- ~~NodeCGのコードを編集する(BANマップの画面を自動生成する)~~
- ~~BANフェーズの画面とタイマーを作る(動画)~~

## 仕様
- ~~/ban "マップ名" でBANマップが設定できるようにする~~選択スロットで選択できるようにする
- ~~/ban reset でリセット → /banreset でリセット~~→banフェーズ終了後時間経過でリセット
- 正しく設定できたら「"マップ名"がBANされました」とbotがチャットを打つようにする

## 作成するプログラムの概要
1.  ~~コマンドが使用される~~banマップが選択される
2. ~~BOTがBANマップの名前をテキストファイルに出力する(BANなしはundefinedを出力) BOTがマップ名を認識して変数に格納する文字列で格納するよりも数字に対応させて格納したほうが良いかも(0=BANなし, 1=ヘイヴン, etc. )初期値を0にしておけばBANなし(コマンド未使用の時)も対応できる？~~ 配信用にvalorantapiのmapidをreplicantに渡す。マップ抽選用にはfilter関数を使う。
4. ~~NodeCGがテキストファイルの内容を読み取る~~ Replicant機能を使って、値がNodeCGに渡される
6. 変数の内容を基に画像を生成
7. 配信に映される

## 使用時の流れ
チーム別VCに移動
配信再開〜

- チーム内で相談が行われ、各チームの代表1人がコマンドを使用する
- BANフェーズには時間制限があり、1分間を予定。時間内にコマンドが使用されなかったらBAN無しの扱いとなる(実況解説の人は1分間トークを頑張って👍)
- BANマップが確定後、BANマップ2つが左右に配置された自動生成画像が配信に乗る(例のリザルト画像の応用)

〜マップ選択へ続く

## 今後の予定
- Q2試験前はアイデアを練る期間にする
- 試験後に製作に取り掛かりたい

やること
killjoy.js

**Comment by ykmtsd** [comment]
使用時の流れを追加

**Comment by secchanu** [comment]
BotをNodeCG上で動作させれば値をReplicantを通してやり取りできるのでテキストファイルは必要なくなります

参考: [Replicant | NodeCG](https://www.nodecg.dev/docs/classes/replicant)

**Comment by ykmtsd** [comment]
NodeCGってそんな便利な機能あるんですね～
bot移植作業もしなきゃ

**Comment by ykmtsd** [comment]
botの移植作業お願いできますか？

**Comment by secchanu** [comment]
移植って言っても言語同じで動く場所もサーバー側で同じなのでほぼそのまま使えますよ

**Comment by ykmtsd** [comment]
> 移植って言っても言語同じで動く場所もサーバー側で同じなのでほぼそのまま使えますよ

got it

**Comment by secchanu** [comment]
NodeCGで画像表示するってなると今このリポジトリの方で実装しているマップ表示と同じ形で実装した方が良いと思うんですけど、どうしても向こうのコード使いたいってことならconfig.iniにパール追加するだけなので好きなように追加してください

**Comment by ykmtsd** [comment]
BOTのプログラムを変更したらどこにアップロードすればいいですか？
KUeSTのDiscordサーバーで動作確認したいです

**Comment by secchanu** [comment]
アップロードするわけじゃなくて自分のPC上で動かしてみてください

KUeSTのサーバーで動かして悪影響出たりするといけないので先にテスト用のサーバー作ってそこで動作確認してみてください

**Comment by ykmtsd** [comment]
たしかにそうですね
自分のテスト用のサーバーにbot入れるとこからやってみます
分からなかったらまた質問します

**Comment by ykmtsd** [comment]
https://github.com/ykmtsd/kuest/bot/src
killjoy.jsのmapbanの部分を追加しました。
discordで/mapbanを実行しても反応がありません。
間違っているところを教えてください。おねがいします。

**Comment by ykmtsd** [comment]
とりあえずボタンを生成する部分だけ作りました

**Comment by secchanu** [comment]
まず最初のボタンを送信してないのでそのボタンを押された処理は反応しません
もう少しコードの勉強から必要かもですね
