### ISSUE TITLE
サムネイル

### ISSUE THREAD

**Issue by Tooooomo** [KU-eSports/kuest-streaming#42]

**Comment by N4K4eight** [comment]
![splatoon3 custom test](https://user-images.githubusercontent.com/109290734/194772844-3d021a9f-3524-4207-ac64-014ab404cd36.png)
ツイート用にと思ってサムネ？的なものを描いたのですが、ガキンチョのお絵描きみたいになってしまいました(´;ω;｀)
ご指導いただけますか！！

**Comment by Tooooomo** [comment]
## レイアウト
とてもいいと思います
要素の重要度に則して各要素の配置や大きさが設定されていてナイスです
VALORANTの時はフレームを付けましたがパキッとした印象になるのでおすすめです

## フォント
デザイン性が高すぎるように感じるのでもう少し可読性を優先してもいいと思います
スプラ3のテキストに使われているフォントは大まかにスプラ1ベースの極太とスプラ2ベースの細めの2種類に分けられますが
どちらもかなり可読性は高いです
公式フォントは~~有志が昔してたけど今は~~配布してないと思うので無料フォントを漁ってたくさん試してみてください

## 背景デザイン・文字効果
インクしぶきは公式の画像にも採用されているデザインというのもありとてもいいと思います
中央のしぶきもロゴと背景の間にメリハリがついて見やすいです 小しぶきのようにもう少し細い足を伸ばしてもいいかも
文字効果ですが前回のサムネでは文字の一部の色を変えたり影をつけたりしてました
可読性を落とさない程度にフォント以外の部分で遊びをもたせてもいいと思います

## 色
今回最大の課題です ちゃっちい感の原因はだいたいここにあるかと

### 背景 
おそらく原色を使っているせいかのっぺりした印象になっています
彩度を落とすか淡い色を使ってみるといいかもしれません
また前回のジェットのように背景に何らかの効果を加えるとのっぺり感は解消できます
イラストでなくても射線の繰り返しなど何らかのパターンで大丈夫です

### しぶきの色
ロゴの色と同じ色を使って色数を抑えているのは好印象です
色数が極端に増えるとごちゃつきの原因になるので使う色は今くらいに抑えておくのがいいと思います
ただ左上のピンクのしぶきだけ色が違うのが気になります
黄色と紫に比べて面積が少ないのが浮いているように見える原因かと
背景と色相が似通っているのもちょっとマイナスに感じます
スプラは~~基本的には~~2チームで戦うゲームなのでしぶきも2色でいいんじゃないでしょうか

### テキストの文字色
上下の文字は中央の大しぶきと同じ黒色なのでぱっと目に入らなくなってしまっていると思われます
白系統の色にするか、縁取りや影を追加することで見やすくなると思います
これは色全体に言えることですが、黒と白は万能の色です ~~オタクはモノトーンが好きなので~~
画面のどこかに黒があるなら白も入れるとメリハリが出ます

### ロゴの色
公式の色である黄色と紫を採用したのは👍です
ただ使い方がよくないからかパっとしない印象になっています
色には進出色と後退色という概念があり(調べてみて)、その使い分けが悪いとアンバランスに見えてしまいます
公式の色使いなども参考にして目を引く表現を目指してみてください

***

長くなってしまいましたが所感です
デザイン面では前回より格段にいいものになっていると思います
色遣いは永遠の課題なのでお互い頑張りましょう
あと念のため！カラーモードはRGBになっていることを確認しておいてください

**Comment by secchanu** [comment]
スプラ2ベースのフォントの漢字部分は「くろがねstd」ってやつです(サイズは調整されてるけど)参考までに
