### ISSUE TITLE
待機画面

### ISSUE THREAD

**Issue by Tooooomo** [KU-eSports/kuest-streaming#43]

**Comment by Tooooomo** [comment]
## 1stラフ
![waiting](https://user-images.githubusercontent.com/104683109/195142578-bc5b998c-7813-476b-9e91-d2e5900cde46.png)
トーク画面がかなり良かったので流用
- 右下のテキストとタイマーはNodeCGで動かす
- 矢印はくるくる回す 画像は用意します

**Comment by secchanu** [comment]
待機中とトーク中が遠目から見て同じだとメリハリつかない気がする

**Comment by Tooooomo** [comment]
## 2ndラフ

![waiting2](https://user-images.githubusercontent.com/104683109/195242455-7a972b27-4a76-4452-b620-6796c391798e.png)

コンクリート壁にインク撃ったイメージで

- しぶきはイラレで作ります
- フレームがほしいけどどうしようか考え中 とりあえずなしで進める

**Comment by secchanu** [comment]
周りにシールとかグラフィティ敷き詰めてフレーム代わりにするの良さそう~~作業量増えるけど~~

**Comment by Tooooomo** [comment]
ちょっと考えた
原型よさそうならとりあえずこれでいってステッカーは後で追加できるようにできる？
他の作業の進み方次第で実装ってことで

**Comment by Tooooomo** [comment]
ステッカー類は高画質画像確保できればそれ使えるかな
無理ならイラレでトレスになります~~なかさん一緒に頑張ろうね~~

**Comment by secchanu** [comment]
ステッカーランダム要素なしで良いと思う(大きさとか向きの問題でランダムだと間隔が綺麗にならないと思う)しフレーム全体で1つの透過画像で用意することになると思うから画像用意側の余裕見てで良いよ
使ってたか覚えてないけど一応イカリングの中見てみるか

**Comment by Tooooomo** [comment]
追加するときはレイヤー的にbgとしぶき(仮にsplat)の間の階層になるから
それを考慮したcssの書き方にする必要があるし実装組は考えておいてほしいかも？

**Comment by Tooooomo** [comment]
waiting-layoutブランチ作って完成した素材から入れていきます  
まずはタイマーとテロップの背景splat入れました

**Comment by Tooooomo** [comment]
グラフィティ試作
読めるかな？
![graphiti_kuest](https://user-images.githubusercontent.com/104683109/197337659-7b482b32-e99f-4efc-ba83-de1c6f91271d.png)

**Comment by Tooooomo** [comment]
## 3rdラフ
![test](https://user-images.githubusercontent.com/104683109/197455489-d4a17f6c-f9a8-45d5-bf00-0628441f9ce9.png)
いくつかステッカー追加したけどこれで完成でいいかな

**Comment by secchanu** [comment]
左下ちょい寂しい気はするけど良い感じだと思う

**Comment by Tooooomo** [comment]
## 決定稿
![Image](https://user-images.githubusercontent.com/104683109/197721166-60843c9a-5826-457f-b6d4-b27a60036b51.png)

これベースでいきます
微調整はバランスみながらでいきましょう

**Comment by Tooooomo** [comment]
素材入れました
背景どうしましょ
薄いグレーのべた塗りだけcssで実装して模様は画像にするのが作業量的にいいですかね
背景にもう手つけてたら申し訳ないんですけど

**Comment by secchanu** [comment]
同じパターンの繰り返し模様だからタイル一つ分(横とか縦に並べたら完成する)の画像入れるとかで良いんじゃないかな

**Comment by Tooooomo** [comment]
作ってみる
とりあえず表層の実装からお願いします
