### ISSUE TITLE
BGM

### ISSUE THREAD

**Issue by Tooooomo** [KU-eSports/kuest-streaming#47]

**Comment by ykmtsd** [comment]
# BGM候補
Splatoon sound trackから選びました
## オープニング
- Splattack!
- Ink or Sink

## トーク
- ハイカラシンカ

## 全体ハイライト
- シオカラ節
- キミ色に染めて

が僕は良いと思いました

**Comment by secchanu** [comment]
## 案
複数のものは再生リストでループ

### 待機画面

- 02 Splattack! (Jam Session)
- 17 プレイヤーメイク
- 19 ハイカラシティ チュートリアル
- 21 ロビー
- 22 Ika Jamaica
- 23 Lookin' Fresh
- 07 アタリメのテーマ
- 08 タコツボバレー
- 17 ミステリーファイル

### トーク画面

- 20 広場


### 全体ハイライト～エンドカード

- 03 キミ色に染めて
- 19 シオカラ節

**Comment by ykmtsd** [comment]
全体ハイライトに音楽流すとゲームの音楽と重複してうるさく感じたので、全体ハイライトは音楽無しでもアリだと思います

**Comment by ykmtsd** [comment]
secchanuさんの案も一部採用して、本番のBGMは次のリストにしようかなと思います。
どうしても入れて欲しい、または消して欲しい曲があれば気軽に言ってください。

## 待機
- Disc1-02 Splattack! (Jam Session)
- Disc1-17 プレイヤーメイク
- Disc1-19 ハイカラシティ チュートリアル
- Disc1-21 ロビー
- Disc1-22 Ika Jamaica

## トーク
- Disc2-01 ハイカラシンカ

## 全体ハイライト
- Disc2-03 キミ色に染めて
- Disc2-19 シオカラ節

## エンドカード
- Disk2-20 マリタイム・メモリー

##その他
全体ハイライトにBGMを付けるとゲームのBGMと混ざってうるさく感じたので、全体ハイライトはBGM無しまたはすごく小さい音量でも良いんじゃないかなって考えてます。
エンドカードにはBGMを付けます。

**Comment by secchanu** [comment]
全体ハイライトのBGMはAdvanced Scene Switcherで音量下げる予定なので大丈夫です
