### ISSUE TITLE
台本

### ISSUE THREAD

**Issue by Tooooomo** [KU-eSports/kuest-streaming#48]

**Comment by N4K4eight** [comment]
# Splatoon3 KUeSTカスタム 進行台本


## 1. OP
皆さんこんばんは。Splatoon3 KUeSTカスタム、解説はKUeST Toomoさん、実況は私同じくKUeST N4K4がお送り致します。今回は、9/9にリリースされた、Splatoon3のカスタムを開催するということで、KUeST初の試みですが、どういった展開を期待しますか？ 
ありがとうございます。

## 2. サークル紹介
さて、ここで、我々KUeSTの紹介をさせていただきます。金沢大学e-sportsサークル【KUeST】は、2022/3/14に創設された非公認サークルです。みんなで楽しくゲームをやりたい！というサー長の私の思いに、たくさんの部員が集まってくれております。現在は、ゲームをプレイするほか、こういったカスタムの開催、その配信や、配信関係のbot制作、プログラミングも行っております。新規部員は随時募集しておりますので、ご興味を持たれた方はぜひ、TwitterのDMやGMailからご連絡ください。企業様、他大学からのご連絡もお待ちしております。

## 3. ルール説明
今カスタムのルールを説明させていただきます。今回は、ナワバリカスタムと題しまして、ナワバリバトルのみのカスタムマッチとなっております。そして、

- ~~12人以下の場合：参加者は、毎回ランダムでチーム分けされ、いろいろなメンバーとマッチしていただきます。~~
- 12人以上の場合：参加者は、ランダムに分けられたチームでリーグ戦を行っていただきます。このカスタムを通してメンバーは固定となります。

## 4. 試合前
（マップ発表）マップが決定したようです。次のマップは、○○です。このマップ、どういった特徴がありますか？
 なるほど。（９０秒）
（８秒）さて、大変長らくお待たせいたしました。（５秒）試合準備の方が整ったということなので、さっそく見ていきましょう。それでは、1stマッチ、スタートです。

## 5. 試合実況
ブキ構成、両チームの強み等

## 6. リプレイチェック＆試合感想
試合結果、キルシーンの感想

## 7. インターバル入り
ここでインターバルを取らせていただきます。配信再開は、（１０分後）を予定しております。それでは、配信再開までしばらくお待ちください。

## 8. インターバル戻り
皆様、大変長らくお待たせを致しました。配信を再開させていただきます。続いては、nthマッチ、マップは○○となっております。このマップは、どのようなマップでしょうか。　
なるほど。（９０秒）~~（１２人以下の場合：先ほどのマッチとはメンバーを入れ替えて行われます。）~~
（８秒）さて、大変長らくお待たせいたしました。（５秒）試合準備の方が整ったということなので、さっそく見ていきましょう。それでは、nthマッチ、スタートです。

## 9. 最後の挨拶、ED
さて、これで最後のマッチが終了となりました。~~（ここって自分の感想ですよ）~~
今回はn試合の開催となりましたが、全体を通して、Toomoさんいかがでしたか？
ありがとうございます。我々も楽しませていただきました。

我々KUeSTは、新規部員大募集中ですので、ご興味ある方は、ぜひご連絡してください。また、企業様、他大学の方からの連絡もお待ちしております。  
それでは、本日のハイライトをご覧いただきながら、お別れとさせていただきます。本日はご覧いただきありがとうございました。また、次回のKUeSTカスタムでお会いしましょう。さようなら。
