### ISSUE TITLE
画面共有の方法

### ISSUE THREAD

**Issue by Tooooomo** [KU-eSports/kuest-streaming#51]

**Comment by ykmtsd** [comment]
secchanu氏が昔おすすめしてたリモートデスクトップソフトを思い出したのでリンクを置いておきます。

低遅延・4K240fpsまで可・無料
parsec
https://parsec.app/

フルHD60fpsで配信するなら十分すぎる性能だと思います。

**Comment by secchanu** [comment]
> secchanu氏が昔おすすめしてたリモートデスクトップソフトを思い出したのでリンクを置いておきます。
> 
> 低遅延・4K240fpsまで可・無料 parsec https://parsec.app/
> 
> フルHD60fpsで配信するなら十分すぎる性能だと思います。

カメラの表示とParsecで同時に使ってみて実際の負荷見てみたいね

**Comment by ykmtsd** [comment]
👍

**Comment by secchanu** [comment]
これ実況解説への画面共有方法解決してなくない？

**Comment by ykmtsd** [comment]
確かにそうですね
急いで解決方法考えます

**Comment by ykmtsd** [comment]
parsecでいけます
ホスト1人に対してクライアントは複数人接続できるので、実況解説の人にもparsec入れてもらうことで解決できます
さっき実験して確認もしました

**Comment by secchanu** [comment]
試合中のカメラについてはそれで良いと思うけどその他リプレイとかはどうする？っていう

**Comment by ykmtsd** [comment]
valoカスタムの時どうやってリプレイを共有してましたか？

**Comment by ykmtsd** [comment]
obsのプレビュー画面をdiscordライブで配信すれば良さそう
